#!/bin/bash -e

# Configuring proxy...
export http_proxy=http://10.131.188.1:80
export https_proxy=http://10.131.188.1:80

source /var/lib/tsuru/base/rc/config

# Update Ubuntu and install unzip and zip
apt-get update &&
apt-get install -y unzip zip --no-install-recommends 

# Download and install SDKMAN
curl -s get.sdkman.io | bash

# Initialize SDKMAN
source "$HOME/.sdkman/bin/sdkman-init.sh"